./countClusters ../webgraph/labels-0.txt 20 --no-comm-sizes
./countClusters ../webgraph/labels-1.txt 20 --no-comm-sizes
./countClusters ../webgraph/labels-2.txt 20 --no-comm-sizes
./countClusters ../webgraph/labels-3.txt 20 --no-comm-sizes
./countClusters ../webgraph/labels-4.txt 20 --no-comm-sizes
./countClusters ../webgraph/labels-5.txt 20 --no-comm-sizes
./countClusters ../webgraph/labels-6.txt 20 --no-comm-sizes
./countClusters ../webgraph/labels-7.txt 20 --no-comm-sizes
./countClusters ../webgraph/labels-8.txt 20 --no-comm-sizes
./countClusters ../webgraph/labels-9.txt 20 --no-comm-sizes
./countClusters ../webgraph/labels-10.txt 20 --no-comm-sizes
./countClusters ../webgraph/labels-11.txt 20 --no-comm-sizes